CREATE TABLE kreatorok (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nev VARCHAR(255) NOT NULL,
    felhasznalonev VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    jelszo VARCHAR(255) NOT NULL
);
